title: "Marcos Augusto"
author: "Marcos Augusto"
description: "Universidade de Brasília"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
sidebar: false
show_excerpts: false      # show article excerpts on the home page
show_frame: false      # adds a gray frame to the site
show_description: false
show_sidebar: false       # show a sidebar instead of the usual header

# Styling

dark_header: false        # always keep the header dark
minimal: false            # use simpler style

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  #- {file: "index.md"}
  #- {title: "Cool Site", url: "https://towardsdatascience.com/"}
  - {title: "Projects", file: "projects.md"}
  - {title: "Blog", file: "blog.md"}
  - {title: "CV", file: "cv.md"}
  - {title: "External Links", file: "external_links.md"}
  #- {file: "cv-marcos_augusto.pdf", title: CV}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:marcosbsb2014@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/MarcosAugusto47"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
